Feat/refactor api
CeresDB/ceresdb-client-go pull request #20
Opened 2023-01-31 03:36 UTC by mrrtree

# Which issue does this PR close?

Closes #

# Rationale for this change
 
 
SDK redesign unified API style

# What changes are included in this PR?

refactor api

# Are there any user-facing changes?

1. Write use new model `Point`, and query use new model `Row` 
2. rename `metric` to `table` 

# How does this change test

all unit test is pass

2023-02-09 04:17 UTC, jiacai2050 requested changes

2023-02-09 04:17 UTC, jiacai2050 commented on utils/query.go
> +			colString, _ := column.(*array.String)
```
t := value.(typeName)
```
This is enough if you don't want to do type check

2023-02-09 04:17 UTC, jiacai2050 commented on types/code.go
> +	ErrPointEmptyTimestamp = errors.New("point timestamp should not be empty")
should large than 0

2023-02-09 04:17 UTC, jiacai2050 commented on types/route.go
> +const (
How about this style?
```
type RouteMode int

const (
        Direct RouteMode = iota
        Proxy
)
```

2023-02-10 08:37 UTC, mrrtree commented on utils/query.go
> +			colString, _ := column.(*array.String)
ok, fixed

2023-02-10 08:38 UTC, mrrtree commented on types/code.go
> +	ErrPointEmptyTimestamp = errors.New("point timestamp should not be empty")
rename to
```go
	ErrPointEmptyTable     = errors.New("point's table is not set")
	ErrPointEmptyTimestamp = errors.New("point's timestamp is not set")
```

2023-02-10 08:38 UTC, mrrtree commented on types/route.go
> +const (
fixed

2023-02-10 08:40 UTC, jiacai2050 commented on types/code.go
> +	ErrPointEmptyTimestamp = errors.New("point timestamp should not be empty")
👍

2023-02-10 08:41 UTC, jiacai2050 commented on examples/read_write.go
> +	for i := 0; i < 2; i++ {
👍

2023-02-10 09:15 UTC, jiacai2050 approved these changes
LGTM

2023-02-10 09:41 UTC, merged